# Generated by Django 3.0.6 on 2020-05-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='op_addr',
            new_name='op_address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='st_addr',
            new_name='st_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
