# Generated by Django 3.0.6 on 2020-05-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200528_1216'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prefix',
            table='prefixes',
        ),
    ]
