# Generated by Django 3.0.6 on 2020-06-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productluggagecolor',
            name='luggage_color',
        ),
        migrations.RemoveField(
            model_name='productluggagecolor',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='color_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='texture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Texture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='luggage_color',
        ),
        migrations.AddField(
            model_name='product',
            name='luggage_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.StockStatus'),
        ),
        migrations.DeleteModel(
            name='LuggageColor',
        ),
        migrations.DeleteModel(
            name='ProductLuggageColor',
        ),
    ]
