# Generated by Django 3.0.6 on 2020-05-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='color_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='luggagecolor',
            name='color_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='color_url',
            field=models.URLField(max_length=2000),
        ),
    ]
