# Generated by Django 3.0.6 on 2020-05-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200527_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.ManyToManyField(through='product.ProductOption', to='product.Handle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='luggage_color',
            field=models.ManyToManyField(through='product.ProductLuggageColor', to='product.LuggageColor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(through='product.ProductOption', to='product.Tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wheel',
            field=models.ManyToManyField(through='product.ProductOption', to='product.Wheel'),
        ),
    ]
