# Generated by Django 3.0.6 on 2020-05-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200527_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_number',
        ),
    ]
