# Generated by Django 3.0.6 on 2020-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
