# Generated by Django 3.0.6 on 2020-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
