# Generated by Django 3.0.6 on 2020-05-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='texture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Texture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.StockStatus'),
        ),
    ]
