# Generated by Django 3.0.6 on 2020-05-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200531_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productluggagecolor',
            name='luggage_color',
        ),
        migrations.RemoveField(
            model_name='productluggagecolor',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='color_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='luggage_color',
        ),
        migrations.AddField(
            model_name='product',
            name='luggage_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='LuggageColor',
        ),
        migrations.DeleteModel(
            name='ProductLuggageColor',
        ),
    ]
