# Generated by Django 3.0.6 on 2020-05-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200531_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texture',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
