# Generated by Django 3.0.6 on 2020-05-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200531_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handle',
            name='color_url',
        ),
        migrations.RemoveField(
            model_name='wheel',
            name='color_url',
        ),
    ]
